name: Jaeminane
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51272
title: Jaeminane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303134'
    - '#dd5694'
    - '#f5f4ef'
    - '#bbbbbc'
    - '#8b8987'
  brandStrength: 0.5
  lightness: 0.05555154616013169
  saturation: 0.92627615458332
  rhythmicContrast: 0.7386225541122258
purpose: []
